# Site settings
title: Hello! I'm Pierre-Emile Ferron
appname: Pef
description: Welcome to my blog. I talk about new things I learn in my journey to become a better software engineer.
url: "https://peferron.com"

# Build settings
markdown: redcarpet
permalink: pretty
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - watch
  - npm-debug.log
defaults:
  -
    values:
      layout: null
