# Site settings
title: Pierre-Emile Ferron
appname: pef
description: >
  Rust, Go, JS, Swift, and getting better at software engineering.
url: "https://peferron.com"

# Build settings
permalink: pretty
markdown: kramdown
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - watch
  - npm-debug.log
defaults:
  -
    values:
      layout: null
