# Site settings
title: Pierre-Emile (Mat) Ferron
description: >
  Personal website of Pierre-Emile (Mat) Ferron. Rust, Go, JS, and getting better at software
  engineering.
url: "https://peferron.com"

# Build settings
permalink: pretty
markdown: kramdown
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - watch
defaults:
  -
    values:
      layout: null
