# Site settings
title: Pierre-Emile (Mat) Ferron
description: >
  Personal website of Pierre-Emile (Mat) Ferron. Rust, Go, JS, and getting better at software
  engineering.
url: "https://peferron.com"

# Blog settings
blog_title: peferron's blog
blog_description: >
  Blog description
  Can be multiline
blog_baseurl: "/blog"

permalink: pretty
markdown: kramdown
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - watch
defaults:
  -
    values:
      layout: null
